### ISSUE TITLE
Mod preview langage (embed and content)

### ISSUE THREAD

**Issue by Densha-Weeb** [APasz/SSCBot#26]
+ langage selection for the mod name / desc (steam data displayed in the embed if available in the steam mod)
+ langage selection/translation for the UI of the embed (for the stuff like 'publish x day ago', 'description', 'updated' and ect)

if you need help for French translation, i can help

**Comment by APasz** [comment]
Text of embed will localisable in v2.7

Non-English description is proving difficult to obtain from Steam.
The only documented way is seemingly broken.
Will update if something can be worked out.

Nexusmods doesn't support multi-language descriptions in the same way Steam does.
Nexus is designed for separate translation mods.

**Comment by APasz** [comment]
v2.7
#37 for mod title/desc
